language: python
sudo: true

python:
  - 2.7

cache:
  pip: true
  directories:
    - buildout-cache

install:
  - virtualenv .
  - bin/pip install --upgrade pip
  - bin/pip install -r requirements.txt
  - mkdir -p buildout-cache/{eggs,downloads}
  - bin/buildout -Nc travis.cfg

script:
  - bin/test
  - bin/coverage 

after_success:
  - pip install coveralls==0.5
  - coveralls

notifications:
  email:
    recipients:
      - devs@imio.be
